package org;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class d323 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public d323() {
    }




}