package org;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dat1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public dat1() {
    }




}